stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest test.py

run_build:
    stage: build
    image: python:3.9-slim-buster
    before_script:
        - pip install -r requirements.txt
    script:
        - python azureml.py
      
run_build:
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: ""
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
    rules:
        - if: $CI_COMMIT_TAG

run_deploy:
    stage: deploy
    script:
        - echo "hello world!"
    rules:
        - if: $CI_COMMIT_TAG